sudo: required
language: bash
dist: bionic
services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - ./scripts/travisDockerSetup.sh

install:
  - docker pull multiarch/qemu-user-static
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker run -d -p 5000:5000 --restart always --name localReg registry:2
  - docker ps -a

script: 
  - make build BRANCH=$TRAVIS_BRANCH GIT_COMMIT=$(git rev-parse --short $TRAVIS_COMMIT) GITHUB_TOKEN=$GITHUB_TOKEN
  - make test_all BRANCH=$TRAVIS_BRANCH

after_script: docker images

before_deploy:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

deploy:
  - provider: script
    script: make build_push BRANCH=$TRAVIS_BRANCH GIT_COMMIT=$(git rev-parse --short $TRAVIS_COMMIT) GITHUB_TOKEN=$GITHUB_TOKEN
    on:
      branch: master
  - provider: script
    script: make build_push BRANCH=$TRAVIS_BRANCH TAG_LATEST=1 GIT_COMMIT=$(git rev-parse --short $TRAVIS_COMMIT) GITHUB_TOKEN=$GITHUB_TOKEN
    on:
      tags: true
      